language: java
script:
  - cd ./simple-api
  - mvn clean verify

  # Connexion à Docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stadin
  # build
  - docker build -t $DOCKER_USERNAME/tp-devops
  #Publication des images
  - docker push $DOCKER_USERNAME/tp-devops

branches:
  only:
    - develop

cache:
  directories:
    - $HOME/.m2
  services:
    - docker

