#playbook avec roles
- hosts: all
  gather_facts: false
  become: yes
  tasks:
  - name: Test connection
    ping:
  roles:
    - docker
    - python
    - network
    - database
    - app
    - proxy